package com.debanjan.currencyconversion.exchange.dummy

import com.debanjan.currencyconversion.exchange.model.ExchangeRatesDomainModel
/**
 * This is dummy data which was used for testing the UI. This is not used in the final
 * Will be deleted in the future
 * If needed will be moved to test folder
 */
internal val dummyExchangeRates = listOf(
    ExchangeRatesDomainModel("AUD", 1.616),
    ExchangeRatesDomainModel("BGN", 1.9558),
    ExchangeRatesDomainModel("BRL", 4.7825),
    ExchangeRatesDomainModel("CAD", 1.5073),
    ExchangeRatesDomainModel("CHF", 1.132),
    ExchangeRatesDomainModel("CNY", 7.8468),
    ExchangeRatesDomainModel("CZK", 25.855),
    ExchangeRatesDomainModel("DKK", 7.4657),
    ExchangeRatesDomainModel("GBP", 0.89203),
    ExchangeRatesDomainModel("HKD", 8.8743),
    ExchangeRatesDomainModel("HRK", 7.4325),
    ExchangeRatesDomainModel("HUF", 321.9),
    ExchangeRatesDomainModel("IDR", 15982.0),
    ExchangeRatesDomainModel("ILS", 4.157),
    ExchangeRatesDomainModel("INR", 81.609),
    ExchangeRatesDomainModel("ISK", 137.9),
    ExchangeRatesDomainModel("JPY", 125.77),
    ExchangeRatesDomainModel("KRW", 1298.0),
    ExchangeRatesDomainModel("MXN", 21.804),
    ExchangeRatesDomainModel("MYR", 4.7805),
    ExchangeRatesDomainModel("NOK", 9.755),
    ExchangeRatesDomainModel("NZD", 1.694),
    ExchangeRatesDomainModel("PHP", 59.985),
    ExchangeRatesDomainModel("PLN", 4.298),
    ExchangeRatesDomainModel("RON", 4.655),
    ExchangeRatesDomainModel("RUB", 74.0),
    ExchangeRatesDomainModel("SEK", 10.461),
    ExchangeRatesDomainModel("SGD", 1.544),
    ExchangeRatesDomainModel("THB", 35.91),
    ExchangeRatesDomainModel("TRY", 6.324),
    ExchangeRatesDomainModel("USD", 1.139),
    ExchangeRatesDomainModel("ZAR", 16.422),
    ExchangeRatesDomainModel("EUR", 1.0),
    ExchangeRatesDomainModel("AED", 4.178),
    ExchangeRatesDomainModel("AFN", 85.9),
    ExchangeRatesDomainModel("ALL", 124.0),
    ExchangeRatesDomainModel("AMD", 554.74),
    ExchangeRatesDomainModel("ANG", 2.043),
    ExchangeRatesDomainModel("AOA", 351.5),
    ExchangeRatesDomainModel("ARS", 43.0),
    ExchangeRatesDomainModel("AWG", 2.07),
    ExchangeRatesDomainModel("AZN", 1.926),
    ExchangeRatesDomainModel("BAM", 1.9558),
    ExchangeRatesDomainModel("BBD", 2.298),
    ExchangeRatesDomainModel("BDT", 95.9),
    ExchangeRatesDomainModel("BHD", 0.428),
    ExchangeRatesDomainModel("BIF", 2070.0),
    ExchangeRatesDomainModel("BMD", 1.139),
    ExchangeRatesDomainModel("BND", 1.544),
    ExchangeRatesDomainModel("BOB", 7.85),
    ExchangeRatesDomainModel("BSD", 1.139),
    ExchangeRatesDomainModel("BTC", 0.0003),
    ExchangeRatesDomainModel("BTN", 79.0),
    ExchangeRatesDomainModel("BWP", 12.0),
    ExchangeRatesDomainModel("BYN", 2.363),
    ExchangeRatesDomainModel("BYR", 22300.0),
    ExchangeRatesDomainModel("BZD", 2.298),
    ExchangeRatesDomainModel("CDF", 1840.0),
)